"""add purchasing and stock operations

Revision ID: 0019
Revises: 0018
Create Date: 2026-10-03 19:24:46.639821
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0019'
down_revision: Union[str, Sequence[str], None] = '0018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tax_identifier', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_suppliers_company_name')
    )
    op.create_index(op.f('ix_suppliers_company_id'), 'suppliers', ['company_id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipts_company_id'), 'goods_receipts', ['company_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_location_id'), 'goods_receipts', ['location_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_supplier_id'), 'goods_receipts', ['supplier_id'], unique=False)
    op.create_index('uq_goods_receipts_document', 'goods_receipts', ['company_id', 'supplier_id', 'document_number'], unique=True, postgresql_where=sa.text('document_number IS NOT NULL AND supplier_id IS NOT NULL'))
    op.create_table('stock_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('counted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_counts_company_id'), 'stock_counts', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_counts_location_id'), 'stock_counts', ['location_id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfers_company_id'), 'stock_transfers', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_from_location_id'), 'stock_transfers', ['from_location_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_to_location_id'), 'stock_transfers', ['to_location_id'], unique=False)
    op.create_table('goods_receipt_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipt_lines_product_id'), 'goods_receipt_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_lines_receipt_id'), 'goods_receipt_lines', ['receipt_id'], unique=False)
    op.create_table('stock_count_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expected_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('counted_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('difference', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['count_id'], ['stock_counts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_count_lines_count_id'), 'stock_count_lines', ['count_id'], unique=False)
    op.create_index(op.f('ix_stock_count_lines_product_id'), 'stock_count_lines', ['product_id'], unique=False)
    op.create_table('stock_transfer_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfer_lines_product_id'), 'stock_transfer_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_transfer_lines_transfer_id'), 'stock_transfer_lines', ['transfer_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_transfer_lines_transfer_id'), table_name='stock_transfer_lines')
    op.drop_index(op.f('ix_stock_transfer_lines_product_id'), table_name='stock_transfer_lines')
    op.drop_table('stock_transfer_lines')
    op.drop_index(op.f('ix_stock_count_lines_product_id'), table_name='stock_count_lines')
    op.drop_index(op.f('ix_stock_count_lines_count_id'), table_name='stock_count_lines')
    op.drop_table('stock_count_lines')
    op.drop_index(op.f('ix_goods_receipt_lines_receipt_id'), table_name='goods_receipt_lines')
    op.drop_index(op.f('ix_goods_receipt_lines_product_id'), table_name='goods_receipt_lines')
    op.drop_table('goods_receipt_lines')
    op.drop_index(op.f('ix_stock_transfers_to_location_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_from_location_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_company_id'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_index(op.f('ix_stock_counts_location_id'), table_name='stock_counts')
    op.drop_index(op.f('ix_stock_counts_company_id'), table_name='stock_counts')
    op.drop_table('stock_counts')
    op.drop_index('uq_goods_receipts_document', table_name='goods_receipts', postgresql_where=sa.text('document_number IS NOT NULL AND supplier_id IS NOT NULL'))
    op.drop_index(op.f('ix_goods_receipts_supplier_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_location_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_company_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index(op.f('ix_suppliers_company_id'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
