"""production orders

Revision ID: 0024
Revises: 0023
Create Date: 2026-10-05 08:01:32.465812
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0024'
down_revision: Union[str, Sequence[str], None] = '0023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('produced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_company_id'), 'production_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_production_orders_location_id'), 'production_orders', ['location_id'], unique=False)
    op.create_index(op.f('ix_production_orders_product_id'), 'production_orders', ['product_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_orders_product_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_location_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_company_id'), table_name='production_orders')
    op.drop_table('production_orders')
    # ### end Alembic commands ###
