"""invoice intake

Revision ID: 0027
Revises: 0026
Create Date: 2026-10-05 08:38:35.919659
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0027'
down_revision: Union[str, Sequence[str], None] = '0026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('alias_key', sa.String(length=300), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_aliases_company_id'), 'product_aliases', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_aliases_product_id'), 'product_aliases', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_aliases_supplier_id'), 'product_aliases', ['supplier_id'], unique=False)
    op.create_index('uq_product_aliases_global_key', 'product_aliases', ['company_id', 'alias_key'], unique=True, postgresql_where='supplier_id IS NULL')
    op.create_index('uq_product_aliases_supplier_key', 'product_aliases', ['company_id', 'supplier_id', 'alias_key'], unique=True, postgresql_where='supplier_id IS NOT NULL')
    op.create_table('invoice_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('extracted', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('mail_message_id', sa.String(length=300), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receipt_id'], ['goods_receipts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'content_sha256', name='uq_invoice_imports_company_file')
    )
    op.create_index(op.f('ix_invoice_imports_company_id'), 'invoice_imports', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoice_imports_status'), 'invoice_imports', ['status'], unique=False)
    op.add_column('companies', sa.Column('invoice_inbox_token', sa.String(length=64), nullable=True))
    op.add_column('companies', sa.Column('invoice_default_location_id', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('invoice_auto_post', sa.Boolean(), server_default='false', nullable=False))
    op.create_unique_constraint('companies_invoice_inbox_token_key', 'companies', ['invoice_inbox_token'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('companies_invoice_inbox_token_key', 'companies', type_='unique')
    op.drop_column('companies', 'invoice_auto_post')
    op.drop_column('companies', 'invoice_default_location_id')
    op.drop_column('companies', 'invoice_inbox_token')
    op.drop_index(op.f('ix_invoice_imports_status'), table_name='invoice_imports')
    op.drop_index(op.f('ix_invoice_imports_company_id'), table_name='invoice_imports')
    op.drop_table('invoice_imports')
    op.drop_index('uq_product_aliases_supplier_key', table_name='product_aliases', postgresql_where='supplier_id IS NOT NULL')
    op.drop_index('uq_product_aliases_global_key', table_name='product_aliases', postgresql_where='supplier_id IS NULL')
    op.drop_index(op.f('ix_product_aliases_supplier_id'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_product_id'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_company_id'), table_name='product_aliases')
    op.drop_table('product_aliases')
    # ### end Alembic commands ###
