"""background invoice reading

Revision ID: 0028
Revises: 0027
Create Date: 2026-10-05 13:01:04.981581
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0028'
down_revision: Union[str, Sequence[str], None] = '0027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_imports', sa.Column('read_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('invoice_imports', sa.Column('next_read_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_invoice_imports_next_read_at'), 'invoice_imports', ['next_read_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_imports_next_read_at'), table_name='invoice_imports')
    op.drop_column('invoice_imports', 'next_read_at')
    op.drop_column('invoice_imports', 'read_attempts')
    # ### end Alembic commands ###
